# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: about
    weight: 05
  - name: Papers
    url: publication
    weight: 10
  - name: People
    url: authors
    weight: 20
  - name: Venues
    url: event
    weight: 22
  - name: Tags
    url: tags
    weight: 25
  - name: Posts
    url: post
    weight: 30
  - name: Variants
    weight: 40
  - name: BibLaTeX
    url: https://raw.githubusercontent.com/QuantumPL/bib/main/biblatex.bib
    weight: 1
    parent: Variants
  - name: BibTeX
    url: https://raw.githubusercontent.com/QuantumPL/bib/main/bbt.bib
    weight: 2
    parent: Variants
  - name: bibtex2html
    url: retro/bbt.html
    weight: 3
    parent: Variants
  - name: BibBase
    url: base
    weight: 4
    parent: Variants
  - name: Mailing List
    url: https://lists.uchicago.edu/web/info/qplv
    weight: 60
  # - name: Contact
  #   url: contact
  #   weight: 60
